### ISSUE TITLE
We lost our trigger on sorting

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#110]

**Comment by mwernimont** [comment]
The trigger only happens once, you have to refresh the app to get it to trigger again. Mine is still working, so hopefully its just a refresh issue.

**Comment by ldecicco-USGS** [comment]
Ah, I see. I've been viewing it on my "long" monitor (regular monitor flipped sideways). I don't think it can trigger then, but if I bring it over to my regular monitor, no problem.
