### ISSUE TITLE
shrink down the jpg thumbnails

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/great-lakes-microplastics#113]
Some of these files are quite large and we are only using them as thumbnails. Two parts to this:

1) make them all the same size
2) make them all small(ish)

**Comment by ldecicco-USGS** [comment]
Is this done?

**Comment by jordansread** [comment]
no

**Comment by mwernimont** [comment]
@jread-usgs this should be taken care of with this #129
