### ISSUE TITLE
References

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#118]
@mwernimont : could you take the ref text in the siteText.yaml and put it in an accordion style table? @eread-usgs said you did it for one of the other vizzes.

**Comment by mwernimont** [comment]
@ldecicco-USGS What is considered reference text in the siteText.yaml (all of it?) and where would you want this accordion table?

**Comment by ldecicco-USGS** [comment]
I was referring to the references I added starting on line:

https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/master/data/siteText.yaml#L104

I'd want it at the very bottom...but above the footer. Does that make sense?

**Comment by mwernimont** [comment]
It does indeed, can do
