### ISSUE TITLE
Spacing between sections

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#131]
Can that space between the welcome and fig. 1 get minimized?

**Comment by eread-usgs** [comment]
@ldecicco-USGS and @mwernimont, we need to deal with a bunch of things like this (e.g., center justified text, 'Welcome' as the title--not specific enough), and others, related to layout/design. I am going to close this issue and start a new one that lists several of those, then set up a quick meeting w Marty to discuss. @ldecicco-USGS let me know if you want to participate, but no need to, Marty should be able to handle most of it.
