### ISSUE TITLE
General design improvements

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#133]
Layout/design
- [x] increase space between title and text -MW
- [x] make **all** text left justified on mobile **and** desktop -MW
- [x] Re-work sections as discussed in the first sprint (Icon and facts come first) -MW
- [x] The textured background is too textur-y... Personally I like it just-ever-so-slightly-off-white, but I also have no eye for design - MW
- [x] Bigger font on the text in the boxes, need to know immediately we are looking at oysters/mussels and not human ears. Make text for the words 'freshwater fish', 'oysters', 'mussels', 'water', 'sediment', 'water' **bolded** in the icon figure. - MW

Text 
- [x] Come up with alternate title text ('Welcome' is not sufficient) -ER
- [x] Remove jargon that is not understandable to general public (e.g., "Relative abundance", "sorption capacity"), unless it is clearly defined in the app. -ER
- [x] River sediments needs to report 'microbeads per square meter' not particles per square meter - ER
- [x]  "How have microplastics been observed in the environment?" Sounds like a methodological lead it- need to re-work this -ER
- [x] need more transition text between figures -ER
- [x] add context to rel abundance pop out, "1.6%" should read "1.6% of microplastics" per @jread-usgs comment below
- [x] add title or legend to rel abundance figure, per https://github.com/USGS-VIZLAB/great-lakes-microplastics/issues/139

**Comment by ldecicco-USGS** [comment]
Not sure if it goes here...but I'm not sure how to format text via the yaml, there's one spot that says 10^6...it would look nicer as 10 superscript 6.

**Comment by jordansread** [comment]
I also don't think there is enough context with the relative abundance fig:
![image](https://cloud.githubusercontent.com/assets/2349007/15690500/6639e626-2749-11e6-8f23-014ab8bc28a7.png)

1.6% of what? what do these percentages mean?

**Comment by aappling-usgs** [comment]
Agree w/ @jread-usgs - can we have one sentence (and maybe the photo of Austin taking samples) to explain where this barchart breakdown comes from?

And can we afford some new text to also explain how this study differs from others - in sampling tribs as well as lakes - and why that's justified/important?

**Comment by jiwalker-usgs** [comment]
@ldecicco-USGS limited html is allowed in the siteText for things like superscript.  In this case putting 10<sup>6</sup> would format the text properly.

**Comment by jiwalker-usgs** [comment]
sorry, that is

```
10<sup>6</sup>
```

**Comment by ldecicco-USGS** [comment]
cool

**Comment by ldecicco-USGS** [comment]
some comments I've heard:

- [ ] The textured background is too textur-y... Personally I like it just-ever-so-slightly-off-white, but I also have no eye for design 
- [ ] Bigger font on the text in the boxes, need to know immediately we are looking at oysters/mussels and not human ears
- [ ] Should we put a link for each of those boxes down to the proper references at the bottom? 
- [ ] More prominently feature a link to the main paper at the beginning, probably needs to be a placeholder until we get a real link.
- [ ] Actual hyper-links to the references (I'll work on getting those)

**Comment by eread-usgs** [comment]
I agree @aappling-usgs about adding in a little more context (1-2 sentences) that will help to tie each section to the next, and give ample context. As of now, there's not enough. I am going to take a try at this tonight and would appreciate review and edits as needed afterwards.

**Comment by mwernimont** [comment]
@eread-usgs I know it says all text left justified, but I don't think the icon text would look all that great if it were left justified with the big number.

**Comment by jordansread** [comment]
agreed. @mwernimont I think that one is fine as-is

**Comment by jordansread** [comment]
closing this once since all the boxes are complete
