### ISSUE TITLE
Relative abundance figure: remove "Tributaries" as the x-axis 

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#139]
"Tributaries" as the x-axis on the stacked bar chart is not necessary because it is the only bar in the figure, and is kind of confusing as shown. Instead, title and caption/legend text should explain that the data are from great lakes tribs.

**Comment by eread-usgs** [comment]
I can work on caption and title text if @ldecicco-USGS removes the label.

**Comment by jordansread** [comment]
@ldecicco-USGS I am going to take this one since I have it at my fingertips

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/15746101/b21aac04-289a-11e6-8956-701270a78dcc.png)
