### ISSUE TITLE
Make relative abundance stacked bar chart centered in SVG

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#141]
Marty is unable to use CSS to make this figure centered on the page. Please use SVG magic to make it centered.

**Comment by jordansread** [comment]
Centered but still have everything peel out to the right?

**Comment by eread-usgs** [comment]
@jread-usgs  I dont know... Marty and I discussed this morning how to make this figure a little more appealing on the page- Marty wanted to try centering it. If you have other ideas, lets hear them.

**Comment by jordansread** [comment]
Here is what centered looks like:
![image](https://cloud.githubusercontent.com/assets/2349007/15759188/6683c45e-28d3-11e6-8f97-ef7e63e1c994.png)

**Comment by ldecicco-USGS** [comment]
Can it be centered on the expanded image?

**Comment by ldecicco-USGS** [comment]
Like, in that picture, I'd eyeball the center at about the 2nd "n" in "Fibers and Lines"

**Comment by jordansread** [comment]
original:
![image](https://cloud.githubusercontent.com/assets/2349007/15759336/e6376192-28d3-11e6-989d-c6c9b56410e2.png)

**Comment by ldecicco-USGS** [comment]
Mine doesn't look that nice, but still prefer what I see now to the centered version above:

**Comment by ldecicco-USGS** [comment]
![image](https://cloud.githubusercontent.com/assets/1105215/15759449/3eb145a4-28d4-11e6-8d5a-1cbc8034d80d.png)

**Comment by jordansread** [comment]
oh, I changed the main.css in mine to use 100% instead of the 760px value that was in there. That is one difference

**Comment by ldecicco-USGS** [comment]
OK, then that's my vote.

**Comment by jordansread** [comment]
kind of splitting the difference here: adding a small left margin buffer:

Either way, if you want to mod it @mwernimont the relativeAbundance.mustache is the file to do it in.

**Comment by jordansread** [comment]
see #153
