### ISSUE TITLE
Mobile format for relative abundance SVG

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#142]
At present, the pop outs when you click on a category are too wide to see on mobile. Need to make this more narrow for mobile, perhaps by removing content such as photos and other explanatory text. This issue depends on https://github.com/USGS-VIZLAB/great-lakes-microplastics/issues/140 getting done.

**Comment by jordansread** [comment]
here is how the mobile version looks now (obviously some formatting needed):
![image](https://cloud.githubusercontent.com/assets/2349007/15746043/6d70c598-289a-11e6-942d-a090e0a30c61.png)

**Comment by eread-usgs** [comment]
Hmmm thats not how it looks on my phone- I see the whole box with photos and all.... @jread-usgs

**Comment by eread-usgs** [comment]
Ok, I saw the other issue related to this one, and it seems like the mobile SVG is not being used, as you said @jread-usgs

**Comment by jordansread** [comment]
I can make this work for mobile, but I think I will prioritize that after the mobile form factor is in place in the viz
