### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#143]
- [x] Should we put a link for each of those boxes down to the proper references at the bottom? 
- [x] More prominently feature a link to the main paper at the beginning, probably needs to be a placeholder until we get a real link.
- [x] Actual hyper-links to the references (I'll work on getting those)

**Comment by ldecicco-USGS** [comment]
@eread-usgs when PR #151 is merged, could you double-check that the links in the text go to the reference they are suppose to go to?
