### ISSUE TITLE
make y axes horizontally oriented

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#155]
These two line, vertically oriented axis labels are pretty hard to read- we need these words to be immediately recognizable to users and they are not as of now. 

@ldecicco-USGS or @jread-usgs not sure which of you would be best suited to deal with this one....

![screen shot 2016-06-02 at 7 34 11 pm](https://cloud.githubusercontent.com/assets/7794368/15764457/0b9e0092-28f9-11e6-88d1-9c69a8b34636.png)

**Comment by eread-usgs** [comment]
Might have to wrap the text a bit more to get there...

**Comment by jordansread** [comment]
Here is what I came up w/:

![image](https://cloud.githubusercontent.com/assets/2349007/15766043/94dd2ef8-2900-11e6-8b4d-2988306fd11c.png)

**Comment by eread-usgs** [comment]
looks good @jread-usgs
