### ISSUE TITLE
Fig three never triggers the `landUse-p2` tag

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/great-lakes-microplastics#157]
This is supposed to show up on the sort trigger:

landUse-p2: >-
  Fragments, films, and foams were more frequent in samples from more urban basins

**Comment by mwernimont** [comment]
well it's not in the file to be triggered, so I think thats the main problem

**Comment by mwernimont** [comment]
@jread-usgs the text you wanted to appear appears thanks to #169. I'm wondering though if we want just that text to switch out, or both as we have it now? Also do you think the sorting trigger takes too long? As in too much scrolling needed?
