### ISSUE TITLE
Default reference list open

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#158]
I mentioned this in the PR...but there are links in the boxes now that go down to the reference section. But, it doesn't work with the default of the references being hidden. Can we either make the default that the references are all shown...do some fancy javascript if the user clicks the link in the boxes to open the ref list, or something else (maybe all the links in the box simply go to the Reference section?)

**Comment by mwernimont** [comment]
fixed with #159
