### ISSUE TITLE
Land-use fig too compressed w/ horizontal y-labels

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/great-lakes-microplastics#162]
Proposal:
![image](https://cloud.githubusercontent.com/assets/2349007/15806769/dde5d264-2b10-11e6-8829-a4b6c2f8c3ff.png)

(was this):
![image](https://cloud.githubusercontent.com/assets/2349007/15806771/e8d4f1dc-2b10-11e6-9314-2a944577baab.png)

Thoughts @eread-usgs @ldecicco-USGS ?

**Comment by eread-usgs** [comment]
👍
