### ISSUE TITLE
each section should fade in with scroll to keep consistent feel

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/great-lakes-microplastics#166]
So, for this:

![image](https://cloud.githubusercontent.com/assets/2349007/15825822/d6180bfa-2bca-11e6-9ee7-6dbcd7446a27.png)

The next text block should have opacity = 0 until trigged. Same w/ the relativeAbundanceFig.

**Comment by mwernimont** [comment]
@jread-usgs should be realized through #168

**Comment by jordansread** [comment]
👍
