### ISSUE TITLE
make stacked bar chart top panel the same size as bottom?

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#174]
Any way the two panels on the land use figure could be the same size? On a smaller screen, the top label and bottom label barely fit on the page. It'd be nice if the whole thing completely fit, to avoid a cramped/awkward feel.

![screen shot 2016-06-09 at 9 28 13 am](https://cloud.githubusercontent.com/assets/7794368/15931205/bbd76dd8-2e24-11e6-806b-e9e2ecc598e3.png)

**Comment by eread-usgs** [comment]
I showed the viz to John Hoffman, who gave some great feedback on the CRB drought viz, and he was using a smaller screen device, and I watched him struggle to get this figure to show up completely on his screen, by zooming out to 75% so he could see the whole thing....

**Comment by mwernimont** [comment]
@eread-usgs I have made adjustments due to the text rearrangements, can we relook at this before any changes are made? Each time new text is added, the graph is manipulated...etc, I have to go and adjust the scroll magic triggers over again. I'm on around the 5th time doing so and would appreciate a relook before more changes were made.

**Comment by mwernimont** [comment]
I also resized the graph to be a bit smaller for screen adaptability as well in the last PR

**Comment by jordansread** [comment]
Again on this, until we are actually using the `-mobile` figs in the html, we are kind of handcuffed. we can easily make some mods which would be best for each device, but only `-desktop` is being used...

**Comment by jordansread** [comment]
Would it make sense to scale this fig based on % of vertical screen extent?

**Comment by mwernimont** [comment]
I always like the % scaling, but idk how that would effect the triggers on each screen. It's not the easiest thing to have the triggers match up on all devices.

**Comment by ldecicco-USGS** [comment]
I know nothing about mobile...I'm closing this issue, but feel free to reopen
