### ISSUE TITLE
Picture side-by-side with text

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#177]
@mwernimont could you put the text on the left, and the river sampling picture on the right in the section:
Microplastics in rivers
I'd guess use the same ratio as the stuff in the section "Where are in our waterways are microplastics found?"

**Comment by mwernimont** [comment]
@ldecicco-USGS just this text "They found that rivers carry many kinds of microplastics, of which microbeads are a surprisingly small fraction.
Instead, fibers averaged 71% of the total number of microplastics particles in these river water samples." ?

**Comment by ldecicco-USGS** [comment]
I was thinking this whole thing would be left of the picture:

```
USGS scientists sampled rivers flowing into the Great Lakes3 to find out which kinds of microplastics are most common in rivers, and which rivers are the most polluted with microplastics. 

They found that rivers carry many kinds of microplastics, of which microbeads are a surprisingly small fraction.

Instead, fibers averaged 71% of the total number of microplastics particles in these river water samples.
```

**Comment by mwernimont** [comment]
👍

**Comment by mwernimont** [comment]
#178 should take care of this @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
perfect
