### ISSUE TITLE
32 particles in great lakes water needs citation

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#181]
I think it will just be to Austin and Steve's citation, but we need a super scripted citation for this one. Otherwise it kind of looks like the citation for the following fact is holds for both. 
![screen shot 2016-06-13 at 7 34 57 pm](https://cloud.githubusercontent.com/assets/7794368/16026722/76385bb6-319e-11e6-8694-03020b9796f1.png)

**Comment by eread-usgs** [comment]
And I think there's already a preliminary citation in place in the list for that, just not with the journal details.

**Comment by ldecicco-USGS** [comment]
Both blurbs are for Austin's paper, right?

**Comment by ldecicco-USGS** [comment]
If so, should we (to be consistent) put a citation for both the oysters and mussels? 
I was originally just putting one citation per "box".

**Comment by ldecicco-USGS** [comment]
So just to clarify @eread-usgs .... citation 3 in your screenshot is Austin and Steve's paper. Do you want the 3 to show up in both factoids? Or, should the >13,000 factoid have a different reference

**Comment by ldecicco-USGS** [comment]
@eread-usgs I'm going to close this issue, and open one that specifically numbers the references at the bottom. If you still think this issue is active, please reopen.
