### ISSUE TITLE
Abundance graph needs legend

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#182]

**Comment by jordansread** [comment]
👍

**Comment by ldecicco-USGS** [comment]
@jread-usgs could you add a legend like this:

![2016-08-10_13-05-33](https://cloud.githubusercontent.com/assets/1105215/17565056/66c27772-5efb-11e6-910c-0fa5e98de5a3.png)

**Comment by ldecicco-USGS** [comment]
If you don't have time, I'll give it a go tonight.

**Comment by jordansread** [comment]
should the legends be the same for both then? Horizontal?

**Comment by ldecicco-USGS** [comment]
well, I was just thinking from a space resource perspective we could fit it there. The words on the top plot might have to shrink too much to go horizontal?

It would make sense to be consistent if possible, but not if we have to squint to read the words.
