### ISSUE TITLE
Possible Fig. 3 change

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#183]
One reviewer thought the land use figure might be more clear in this format:

![2016-06-21_13-54-29](https://cloud.githubusercontent.com/assets/1105215/16242388/c9d8315a-37b7-11e6-86aa-690086a33565.png)

@lindsaycarr could you set up the basic `gsplot` object to explore if that's a good idea? 

I wouldn't delete that older code (that created the stacked bars), but just put it together so we can make a decision later.

**Comment by lindsayplatt** [comment]
- [ ] gsplot basic graphs for the individual microplastic types
- [ ] svg-ify the new graphs (@jread-usgs)

Laura recommends keeping the landuse graph on top of the mega-stack graph (instead of on the bottom where it currently is)

**Comment by jordansread** [comment]
Is it possible for me to veto this effort at this point? I don't think it is a better way to display the data and is challenging to fit on landscape screens without making the figures very small.

**Comment by lindsayplatt** [comment]
I was planning to start working on it this afternoon. So if we are going to veto, I would prefer that to be soon. 

I agree though @jread-usgs. Doing this would remove the advantage of our viz vs the static graphs in the paper - you can hover over each bar to get that same information

**Comment by jordansread** [comment]
vetoed.
