### ISSUE TITLE
trigger content sooner

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#185]
"The “appearing” content is a bit disorienting. Subconsciously, when I don’t see content lower on the page, I think there is no more content. I’d recommend either getting rid of it, or at least moving the triggers higher so that there is less white space before the items appear."

I agree with this. @jiwalker-usgs  or @mwernimont can we address this easily? Honestly, I think there's a time and a place for having things magically appear, but this might not be one. On the other-hand, if it's a really tricky thing to undo at this stage, we can live with it.

**Comment by mwernimont** [comment]
Yeah we can just get rid of the fade. Want it gone?

**Comment by ldecicco-USGS** [comment]
yeah

**Comment by mwernimont** [comment]
Asked JWalks to look it over, but the PR for no fades is right here, #187
