### ISSUE TITLE
Remove whitespace

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#194]
There always seems to be excessive whitespace between the figures. If there's a way to not use percentage of screen to determine placement, that would be my vote:

![2016-08-02_16-04-31](https://cloud.githubusercontent.com/assets/1105215/17345285/e1125d30-58ca-11e6-8328-6ad118a3a979.png)

**Comment by mwernimont** [comment]
@ldecicco-USGS So I don't see these giant white spaces on my local version, are you viewing this on your vertical monitor?

**Comment by mwernimont** [comment]
If you are that'd be why theres giant spaces, and how many people would view it on a monitor like it would be my question?

**Comment by ldecicco-USGS** [comment]
OK, what's interesting to me I guess is that if I drag my window over to my normal monitor, and then resize the window to something typical, the excessive whitespaces remain. If I hit refresh, then they get better...I didn't realize I'd have to refresh (so up until now, I thought it was bad on both monitors.)
