### ISSUE TITLE
Make title bigger?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#198]
"I guess I would have expected something centered over the rest of the content, and maybe bigger.  Guess that’s personal preference though"

If it's something you think should be fixed up @mwernimont ...have at it.

**Comment by ldecicco-USGS** [comment]
And if you like it as is, just close the issue.

**Comment by mwernimont** [comment]
@ldecicco-USGS #200 Made the title bigger and put it in a new place. Too white now without the blue line?

**Comment by ldecicco-USGS** [comment]
Looks good to me. Thanks for the speediness
