### ISSUE TITLE
design: take off dark outline on 1st bar chart pop outs, make boxes same color

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#202]
Looks like we are doing some final clean up. In order to make this figure consistent with the look and feel of the rest of the viz, I recommend a few changes to the first barchart. I'm not sure who can tackle this but maybe @mwernimont @ldecicco-USGS or @jread-usgs 

1) make the fill of all of the pop outs the same (as of now constant and mouse-over pop ups have different background)
2) take off the outline on big and little boxes (no line)
2) make the fill a medium light gray
3) make the text white

Current colors / font
![screen shot 2016-08-04 at 3 21 11 pm](https://cloud.githubusercontent.com/assets/7794368/17415285/2e3d9844-5a57-11e6-84ea-e298d11094dc.png)

Recommended colors / font

![screen shot 2016-08-04 at 3 25 55 pm](https://cloud.githubusercontent.com/assets/7794368/17415414/c6ddf4c2-5a57-11e6-9595-10e4461fd0f4.png)

**Comment by eread-usgs** [comment]
And I know this does break somewhat wiht the rest of the viz, in that all of the other text is just clean black text on white background, but those dark outlines make it look less clean and modern, as does the inconsistent fill. Open to other ideas if people have them.

**Comment by ldecicco-USGS** [comment]
Also, @wdwatkins had a suggestion to add links to wikipedia or other sources for some of the more confusing words (oxidative stress for example). Also, maybe have a heading above the examples that says..."Examples"

I spent a little time trying to figure out how to do both of those, and couldn't quite make it work. But if we do start messing with this figure, those would be other good things to add.

**Comment by ldecicco-USGS** [comment]
@jread-usgs ...if I wanted to try to include links, would that be in the "relativeAbundance-xx.json" files? It's not looking at the siteText.yaml ?

**Comment by jordansread** [comment]
That's where they would be, yes. But not sure if <a> works in there..?

**Comment by ldecicco-USGS** [comment]
Sorry....I'm confused "But not sure if works in there" means you are not sure if links would work in svg? or something else..?

Also...confused (due to my poorly worded question) by "That's where they would be, yes"...to update the text in that figure, I update the json files, correct?

**Comment by jordansread** [comment]
Not sure you can use > chars in Json.

Yes, update that file to change the text. 

Oh I see above it cut out my < in the comment

**Comment by ldecicco-USGS** [comment]
got it! mental note: check raw comments if confused, this has happened multiple times for me.

**Comment by ldecicco-USGS** [comment]
@jread-usgs can you take care of the style issues @eread-usgs brought up here?

**Comment by jordansread** [comment]
Yes, will do
