### ISSUE TITLE
Add picture breaks

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#206]
Some great full resolution images are here:
M:\QW Monitoring Team\GLRI toxics\Microplastics\VizPhotos 

@mwernimont do you want to use your professional eye to pick out ones for the "chapter breaks"?  I have a few favorites, but don't know if the need to be in a certain rotation or cropped or something.

**Comment by mwernimont** [comment]
@ldecicco-USGS I'd prefer you choose the ones you like and if theres an issue with one we can discuss and get a different one if needed.

**Comment by ldecicco-USGS** [comment]
OK, I pushed up some pictures to the repo. My recommendations (at least to start) are to add them:

Pictures:
1. "Microplastics in our waterways" = bad_ds_oct2015.jpg
2. "Where in our waterways are microplastics found?" = whereInWater.jpg
3. "What are the known risks of microplastic pollution?" = knownRisks.JPG
4. "Can we kick the microplastics habit?" = kickHabit.jpg
5. "Microplastics in rivers" = microInRivers.jpg
6. "How are plastics getting into our rivers?" = howArePlastics.jpg
7. "What's next?" = whatsNext.jpg

**Comment by ldecicco-USGS** [comment]
Alt text:

bad_ds_oct2015.jpg = "Late fall on the Bad River in WI"

whereInWater.jpg = "USGS scientist sampling for microplastics on the Nemadji River in WI"

mpsampling.jpg = "Microplastic samples"

kickHabit.jpg = "Sampling on the Milwaukee River as the water enters Lake Michigan"

microInRivers.jpg = "Scientists wading for microplastics samples on the Manitowoc River"

howArePlastics.jpg = "View of Milwaukee, WI from Lake Michigan"

knownRisks.JPG = "Canoe floating on the Montreal River"

whatsNext.jpg = "Motor boat microplastic sampling on the Milwaukee River at the Mouth"

**Comment by mwernimont** [comment]
@ldecicco-USGS I will get on this, this afternoon.

**Comment by ldecicco-USGS** [comment]
Awesome! Let me know if there's anything I can help with. Feel free to do whatever you want cropping-wise.

**Comment by mwernimont** [comment]
@ldecicco-USGS So unfortunately the microinrivers and the kickthehabit photos that were picked probably aren't going to work out. Since they have a portrait orientation over a landscape orientation. I could crop it fit the sizes I have picked out for the others ones, but will most likely not be what you wanted to convey with the image, since a large chunk would be taken out of its height.

**Comment by mwernimont** [comment]
![croptry01](https://cloud.githubusercontent.com/assets/6390096/17527725/1fdd8118-5e32-11e6-8758-3f75b664fd6d.jpg)
![croptry02](https://cloud.githubusercontent.com/assets/6390096/17527726/1fdef0ac-5e32-11e6-8cfc-febff65abdf8.jpg)

**Comment by mwernimont** [comment]
Theres the ability to crop at different section of the images, but the orientation would be like this either way

**Comment by ldecicco-USGS** [comment]
I'll add a few others that might work better, although what you pasted here is not too bad either
