### ISSUE TITLE
slight rotation on background

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/great-lakes-microplastics#215]
I'm not the only one in the world that cringes when the horizon is angled:

![image](https://cloud.githubusercontent.com/assets/2349007/17561184/8181e702-5eea-11e6-8ee0-176c42d5254d.png)

**Comment by jiwalker-usgs** [comment]
Or maybe you are...

**Comment by mwernimont** [comment]
I actually think I can fix that.

**Comment by mwernimont** [comment]
![howareplastics](https://cloud.githubusercontent.com/assets/6390096/17564731/247e88ca-5efa-11e6-8b87-0e16ed4b4b9b.JPG)

@jread-usgs Hows this treat your OCD?
