### ISSUE TITLE
Photo contrasts

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#219]
@mwernimont I know nothing about publishing pictures, but feel free to use photoshop to sharpen contrast or do whatever it is that graphic designers do to enhance the keynote pictures. If you think they're good as is, feel free to close this issue.

**Comment by ldecicco-USGS** [comment]
In general, all the pictures seem darker than the originals:

![2016-08-10_13-15-05](https://cloud.githubusercontent.com/assets/1105215/17565301/8918cc6c-5efc-11e6-99c8-96d2dc9f3fad.png)

**Comment by mwernimont** [comment]
@ldecicco-USGS Thats a dimmer div I put on the keynotes to make the text easy to read. The picture hasn't lost any sharpness. :) Its just a div with a black opacity over it to help the white text pop.

**Comment by ldecicco-USGS** [comment]
I'd vote to make the white text a big bigger (and maybe bolder, ie thicker?) and lose the dimmer...the pictures all are dramatically darker. They look so dreary compared to the originals...

**Comment by mwernimont** [comment]
I can do that too if you like

**Comment by ldecicco-USGS** [comment]
Let's do it.

**Comment by jordansread** [comment]
I like the dimmer effect personally

**Comment by mwernimont** [comment]
Well its easy to put back in if you guys confer and decide to go back

**Comment by jordansread** [comment]
The reason we used a div overlay for this is so we could easily change the overlay opacity. Just set opacity to 0 if you want the regular image.

**Comment by mwernimont** [comment]
Then you just useless code sitting there if you never want it back. I think its you want it or ya don't type of situation

**Comment by mwernimont** [comment]
We also did the div overlay to make it an easy photo exchange over me having to put a dim of the photos themselves

**Comment by jordansread** [comment]
fair enough. Yep

**Comment by jordansread** [comment]
Really just depends what you are using the background images for. Is it supposed to be informative and share some detail, or be a true background that is supposed to emphasize the chapter text.

**Comment by mwernimont** [comment]
I personally see the text more important than the BG, but thats just me, which I see the dimmer emphasizing.

**Comment by ldecicco-USGS** [comment]
OK, I played around a little in Firebug, and would offer a compromise of keeping the dimmer but reducing it to 0.2 with the bigger font. So, I'll close that PR and submit a new one.
