### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#220]
Can we across the board make the font size a bit bigger? Whatever the climate-change-walleye-bass size is using, I think that would be better.

**Comment by mwernimont** [comment]
![vision-problems](https://cloud.githubusercontent.com/assets/6390096/17565594/b37e0a3e-5efd-11e6-8476-ca300700f66f.jpg)

I sure can 😄

**Comment by ldecicco-USGS** [comment]
I like it. I pushed it to dev. The headers are now the same size as the paragraphs, and the bullet points are still small. That being said, I think it looks fine that way, so I'm going to close the issue. But, have a look and if you disagree, you can feel free to do another pull request with some more fancy css updates.
