### ISSUE TITLE
Add image to conclusion 

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#228]
I was hoping to do this on my own, but I don't know what's the deal with the References. I pushed my code already, @mwernimont could you have a look?

![2016-08-11_10-12-11](https://cloud.githubusercontent.com/assets/1105215/17593684/57a7d58c-5fac-11e6-99d0-b5f4d34cfd65.png)

**Comment by jordansread** [comment]
censored plover
