### ISSUE TITLE
title for coaster picture

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#234]
Any idea why the title isn't showing up for the coaster (fish) picture? If I inspect the element, it's there. It's a pretty large resolution picture, should we make it a smaller file size, lower resolution?

**Comment by ldecicco-USGS** [comment]
And sampling picture.

**Comment by ldecicco-USGS** [comment]
From @jiwalker-usgs "the div with the text is covering it, you can get the title to show up if you hover over the top of the picture"

I don't know how to fix this.

**Comment by mwernimont** [comment]
Can look into it

**Comment by mwernimont** [comment]
@ldecicco-USGS #236 This fixed it for me

**Comment by ldecicco-USGS** [comment]
Boom
