### ISSUE TITLE
Images totally zoomed in on ipad

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#247]
Only the keynotes images.

**Comment by ldecicco-USGS** [comment]
Same with climate viz

**Comment by mwernimont** [comment]
@ldecicco-USGS Will get on this after lunch

**Comment by mwernimont** [comment]
@ldecicco-USGS No ipads in the office apparently, so will work on this tomorrow am.

**Comment by mwernimont** [comment]
@ldecicco-USGS This was merged. #250 So ipad should look normal. And we should remember as group to remind me next time we do parallax that we need this for ipad. ;)

**Comment by ldecicco-USGS** [comment]
Thanks! Are you doing the same for fish? @jiwalker-usgs ...can we bake it into the package so we don't need to remember?

**Comment by ldecicco-USGS** [comment]
nevermind....I see it

**Comment by jiwalker-usgs** [comment]
@ldecicco-USGS we are switching up the keynotes to a more general template, so we'll be able to include some css with that to take care of it.  I'll make an issue so it isn't lost.
