### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#5]
Make folders (on same level as layout):
scripts
  folders to indicate things like download/munge/process/visualize/tie it all together/etc...
data
  (make approach? cache folder)
figures
   (different filenames or folders for each figure: IE, mobile, desktop)
text
images

Top level: vis.yaml

**Comment by jiwalker-usgs** [comment]
I decided to leave out figures (since these should be generated and not checked into source control) and text (I'm not sure about this, I think just putting that in data should suffice).
