### ISSUE TITLE
Big picture: look and feel

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#6]
Colors, fonts, css, user experience, consistent triggers, figure dimensions / aspect ratio, etc.....

Let's keep this issue open to add more that come up.

This team is @mwernimont  @eread-usgs @jiwalker-usgs

**Comment by lindsayplatt** [comment]
functions = camel case (`mungeRelativeAbundance`)
variables = dots (`raw.data`)
files= underscores (`munged_relative_abundance.json`)
