### ISSUE TITLE
share hex colors w us all

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/great-lakes-microplastics#61]
- [x]  5 main colors
- [x]  plus some extra colors
- [x]  red yellow and green for land use

**Comment by mwernimont** [comment]
![colors](https://cloud.githubusercontent.com/assets/6390096/15302485/da613914-1b78-11e6-966f-55b8d8dfe9c5.jpg)

**Comment by mwernimont** [comment]
Main colors from the picture, will look into the other 3 soon

**Comment by mwernimont** [comment]
![colors](https://cloud.githubusercontent.com/assets/6390096/15326072/361ac510-1c12-11e6-9e9e-50363407a1ce.jpg)

**Comment by mwernimont** [comment]
thoughts?

**Comment by lindsayplatt** [comment]
group decided the two dark colors are a little too similar

**Comment by ldecicco-USGS** [comment]
Do we want 2 colors for text over the colors? White is fine for the darker colors, but maybe we need a darker text color for the text on top of the light blues.

**Comment by mwernimont** [comment]
![colors](https://cloud.githubusercontent.com/assets/6390096/15333147/1b774ea6-1c2e-11e6-9b36-9c3eb67f93f0.jpg)

**Comment by mwernimont** [comment]
![colors](https://cloud.githubusercontent.com/assets/6390096/15333152/21a48a32-1c2e-11e6-82fe-8ee29808e8c1.png)

**Comment by mwernimont** [comment]
Hows that contrast?

**Comment by lindsayplatt** [comment]
what I used for the types in fig 3 (based on Laura's fig 1, but with marty's updated color)

Pellet = #aadedc
Film = #26b9da
Foam = #01b29F
Frag = #4ebec2
Fiber = #0b516b

**Comment by lindsayplatt** [comment]
Does anyone think it is still hard to tell?

![image](https://cloud.githubusercontent.com/assets/13220910/15334148/8f16d684-1c32-11e6-898e-5b33e7368ada.png)

**Comment by mwernimont** [comment]
looks sharp!

**Comment by lindsayplatt** [comment]
looks cleaner when the black outlines aren't there, but then things get difficult to distinguish

![image](https://cloud.githubusercontent.com/assets/13220910/15335914/c5bed04a-1c39-11e6-8d04-4b3a9da8b566.png)

**Comment by lindsayplatt** [comment]
updated color and re-ordered plastic types with #80 
Pellet = #4ebec2
Film = #0b516b
Foam = #01b29F
Frag = #aadedc
Fiber = #26b9da
