### ISSUE TITLE
Chapter 1: Flowing plastic types...

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#7]
So, start with each type being equal (circle?), with explanation over what they are. Then they collapse into the stacked bar. 

See if there are pictures of each kind?

**Comment by ldecicco-USGS** [comment]
Initially, it will automatically come together, then you can hover on the bars to pop out the circle that made that bit.

**Comment by jordansread** [comment]
@mwernimont am going to assign a breakout task from this

**Comment by lindsayplatt** [comment]
desktop:
- stacked bar + circles
- hover over circle & opacity for square and circle increase, plus percentage pops up in circle

mobile:
- same as desktop but with no hover capability (percentage already shown in circle)

nice to have:
- lines connecting circle to bar on hover (desktop)
- static table next to stacked bar + circles
- table is dynamic and reacts to hover in stacked bar/circle and pulls up correct definition
