### ISSUE TITLE
create unSort json list

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/great-lakes-microplastics#72]
For getting back to the original position in the landuse fig (which is sorted based on longitude I think?).

@aappling-usgs do you have bandwidth for this?

**Comment by aappling-usgs** [comment]
reopening because still need EventListener

**Comment by ldecicco-USGS** [comment]
I think it's OK to leave this as once it's sorted...that's it. Future SVGs can get fancier....
