### ISSUE TITLE
Footer Content

### ISSUE THREAD

**Issue by mwernimont** [USGS-VIZLAB/great-lakes-microplastics#78]
Do we have any ideas what we want in the footer?

**Comment by ldecicco-USGS** [comment]
No idea.

**Comment by ldecicco-USGS** [comment]
@jread-usgs do you want @mwernimont to try to make a multi-purpose USGS-VISLAB footer? Snag some/most of the content on the general USGS footer?

**Comment by jordansread** [comment]
yes please.

**Comment by ldecicco-USGS** [comment]
Can we get this finished? Should we just take out the line "URL: http://vizzy.awesome.com"....or do we want/need to get it more inline with other USGS pages?
