### ISSUE TITLE
post-sprint tasks

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/great-lakes-microplastics#82]
**MVP**
- [x] trigger for fig 3 @jread-usgs 
- [x] pin figure 3 @jiwalker-usgs 
- [x] fig 1 hovers @ldecicco-USGS 
- [x] static table for fig 1 @lindsaycarr
- [ ] add more text @ldecicco-USGS 
- [x] figures into html @jiwalker-usgs 
- [x] push css for table for fig 1 please @mwernimont 
- [x] put "data/envEffectsData.csv" info into siteText.yaml
- [x] create layout/templates/mustache file for references
- [ ] hosting @jiwalker-usgs 
- [ ] social media @lindsaycarr 

**Nice to have**
- [x] dynamic table for fig 1
- [ ] more formatting 
- [ ] footer

**Comment by mwernimont** [comment]
PR created for the table CSS

**Comment by ldecicco-USGS** [comment]
Closing this and making individual tasks
