### ISSUE TITLE
Figure 3 Firefox/IE issues

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#85]
Neither IE or firefox show the bars in Fig. 3 top panel.

**Comment by ldecicco-USGS** [comment]
@jiwalker-usgs  also has margin issues too, but we can't replicate that outside of his computer....

**Comment by ldecicco-USGS** [comment]
@jread-usgs have you been able to see this on the Mac?

**Comment by jordansread** [comment]
Fix in #91
