### ISSUE TITLE
Chapter 3: Land use figure

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/great-lakes-microplastics#9]
- Be sure to include more text on other hypotheses...verbatim on bullet points:
  From fact sheet:

```
• Fibers were present in watersheds with all types of land use
and varying wastewater effluent contributions
• Fragments, films, and foams were more frequent in samples
from more urban basins (fig. 2)
```
- Must have: look cool when sorted
- Must have: Start with west -> east, then sort to urban? easy trigger
- Nice to have: Hover would have ave. conc. and type or land type info
- No prompt 

gsplot/munge @lindsaycarr
- [x] move data manipulation code to the munge function
- [x] new visualize function for creating gsplot object
- [x] return two gsplot objects
- [x] change "at" for axis labels (it's overplotting)

dinosvg @jread-usgs 
- [x] svg stuff?

**Comment by ldecicco-USGS** [comment]
1. Create gsplot
2. In gsplot object, annotate each site key
3. Render with dinoSVG as structured SVG
4. Define quick sort (pretty sort)
5. Write javascript to make it flip states

**Comment by ldecicco-USGS** [comment]
Data for the top part of the graph is there. I'll work on getting the rest of the land use for the bottom part. 

@lindsaycarr will start working to make this work in gsplot:

```
fname <- c("cache/All_data_for_data_release.csv",
           "cache/SI_Table 1_site_characteristics_for_PUB_2.xlsx")

mungeLandUse(fname)

library(ggplot2)

conc.summary <- read.table("cache/mungeLandUse.tsv", sep = "\t")

# urban order:
ggplot(conc.summary, aes(x=reorder(shortName, UrbanPct), y=conc_per_m3, fill=type))+
  geom_bar(stat="identity", colour="black") +
  ylab("Average concentration, in particles/cubic meter") +
  xlab("Sampling locations in increasing urban order, left to right") +
  scale_fill_brewer(palette="Accent", labels=c("Fragment","Pellet/Bead","Fiber/Line","Film","Foam","Other"))+
  labs(fill="Plastic type")+
  guides(fill=guide_legend(reverse=TRUE))+
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5))+
  theme(legend.position=c(0,1), legend.justification=c(0,1),
        legend.title=element_text(size=rel(1.3)),
        legend.text=element_text(size=rel(1.3)),
        axis.text.x = element_text(size=rel(1.5)),
        axis.text.y = element_text(size=rel(1.5)),
        axis.title.y = element_text(size=rel(1.3)),
        axis.title.x = element_text(size=rel(1.3)))


```

**Comment by lindsayplatt** [comment]
- [x] move data manipulation code to the munge function
- [x] new visualize function for creating gsplot object
- [x] return two gsplot objects
